patternkit_media_library.settings:
  type: config_object
  label: 'Patternkit Media Library Module Settings'
  mapping:
    use_styles:
      type: boolean
      label: 'Boolean that sets whether to load bundled styles for the media library browser.'
